# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./helmrepository.yaml"
  - "./helmrelease.yaml"
  - "./storageclass.yaml"
configMapGenerator:
  - name: longhorn-chart-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
