# https://github.com/longhorn/charts/blob/v1.10.x/charts/longhorn/values.yaml

defaultSettings:
  concurrentAutomaticEngineUpgradePerNodeLimit: 1
  defaultDataLocality: "best-effort"
  defaultDataPath: "/var/mnt/data"

longhornUI:
  replicas: 1

persistence:
  defaultClass: false
  defaultClassReplicaCount: 3
  defaultDataLocality: "best-effort"

metrics:
  serviceMonitor:
    enabled: true
    interval: 1m
