# yaml-language-server: $schema=https://json.schemastore.org/kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./fluxinstance.yaml"
  - "./github-key.secret.sops.yaml"
  - "./homelab-vars.secret.sops.yaml"
  - "./configmap.yaml"
  - "./gitrepository.yaml"
