# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/grafana.integreatly.org/grafanadatasource_v1beta1.json

apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector: {}
  datasource:
    name: Alertmanager
    type: alertmanager
    url: "http://alertmanager-operated.monitoring.svc.cluster.local:9093"
    access: proxy
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
