# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./kubelet-csr-approver/ks.yaml"
  - "./metrics-server/ks.yaml"
  - "./node-feature-discovery/ks.yaml"
  ###
  - "./security-resources/ks.yaml"
