# https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/values.tmpl.yaml

deployment:
  priorityClassName: system-cluster-critical
  replicas: 1

# https://gateway.envoyproxy.io/docs/api/extension_types/#envoygateway
config:
  envoyGateway:
    provider:
      type: Kubernetes
    logging:
      level:
        default: info

service:
  type: "ClusterIP"
  externalTrafficPolicy: Cluster
