# yaml-language-server: $schema=https://json.schemastore.org/kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./ciliumnetworkpolicy.yaml"
  - "./helmrelease.yaml"
configMapGenerator:
  - name: blocky
    files:
      - configuration.yaml
  - name: blocky-chart-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
