# yaml-language-server: $schema=https://json.schemastore.org/kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./secret.sops.yaml"
  - "./externalsecret.yaml"
  - "./clusterrole.yaml"
  - "./clusterrolebinding.yaml"
  - "./configmap.yaml"
  ###
  - "./grafana.yaml"
  ###
  - "./datasources/alertmanager/grafanadatasource.yaml"
  - "./datasources/prometheus/grafanadatasource.yaml"
  ###
  - "./dashboards/blocky/grafanadashboard.yaml"
  - "./dashboards/cert-manager/grafanadashboard.yaml"
  - "./dashboards/kubernetes-apiserver/grafanadashboard.yaml"
  - "./dashboards/kubernetes-global/grafanadashboard.yaml"
  - "./dashboards/longhorn/grafanadashboard.yaml"
  - "./dashboards/prometheus/grafanadashboard.yaml"
generatorOptions:
  disableNameSuffixHash: true
