# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana
stringData:
  admin-user: ENC[AES256_GCM,data:zhCI0FecaV35Qu8iFQ==,iv:xkNQ2Et3zUGHFHhNijASS7u0zs1qlt3TGenN4b78IkE=,tag:ifRG/sqa7svrO+S96wevJg==,type:str]
  admin-pass: ENC[AES256_GCM,data:zT8eI63bbPBjNi60l2FerPCLKufgoMx61FiwFIaU3K2wh8RUsM/rMg==,iv:+0wgJccSU8uLLCmv6DaRID/0uNpirbTjUeD0IdiwYzU=,tag:qBzTTPzMdUpA/fKGyoFcew==,type:str]
sops:
  age:
    - recipient: age1avqzr4clyk00gzdrphyn560dtuh7t8r8a2qcmwx6trhgxf4qcyfs8n9al3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN3FIdFNsQ1JHYjh1M0RD
        Uk5Vc0UyR2RyOHBKV2Fud3p1RXYvYnEwckM4CjBWT2lUUUpQbnRzQkoydnBUcG5u
        ZituYmpGNlZwRzNYUUFUTmNEL3Mxd1UKLS0tIHJCdWhZNmoxaDRRWEhPQTA0cWhs
        UW1ITjF3em1mbjhuZVM0UVVwVXdKTFUKgjGTTkOvRlQHXGOtTQKRGu8TICBmklRz
        ajmSWNhsXkqvyZoshiXDTfZhHt4M+IRJt4dpArrOANnNY1+e2XY/kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-03T02:36:15Z"
  mac: ENC[AES256_GCM,data:oxfb459W+uSxYgiOR0pS1DDicXuReuptj8wGs6PWQfzXiuAKpF8Ia9bN49B9f5O3b9u3omMqjA+xXKUW+NhSziuyweQr7e5LgBiGGja3EQH9PaND2+//Jeb2f5RZKVBGYi+sJCFLsl1FEBPFJ4rlnyZh/cGTsaFXhx7OpLGYoJk=,iv:61aIDb5JXiTCwX9dKeCWJx+aQ7wQ03jnEupxctUihTM=,tag:9QTE3r+VOKF0DWKGglJ7NA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
