# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./namespace.yaml"
  ###
  - "./kyverno/ks.yaml"
  - "./kyverno-pod-security/ks.yaml"
  - "./kyverno-policies/ks.yaml"
  - "./policy-reporter/ks.yaml"
