# yaml-language-server: $schema=https://json.schemastore.org/kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./helmrepository.yaml"
  - "./helmrelease.yaml"
  - "./service.yaml"
  - "./ingress.yaml"
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: seaweedfs-chart-values
    files:
      - values.yaml
